server:
  port: 8080
jwt:
  secret: mysecretkeymysecretkeymysecretkey123456
  expiration: 3600000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG