spring:
  application:
    name: platform-service
  flyway:
    enabled: true
    locations: classpath:db/migration

  profiles:
    active: dev

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,prometheus
#
#  endpoint:
#    health:
#      show-details: always

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG

  pattern:
    console: "%d %-5level [%X{traceId}] %logger{36} : %msg%n"
