server:
  port: 8082

spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/platform_db
    username: admin
    password: admin

    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true


  data:
    redis:
      host: localhost
      port: 6379


    properties:
      hibernate:
        format_sql: true